export const metadata = {
  title: 'Guest area',
  description: 'Generated by Next.js',
}


function page() {
  return (
    <div>
      <h2 className="font-semibold text-2xl text-accent-400 mb-7">
        Welcome, Safwan
      </h2>
    </div>
  )
}

export default page
